#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/haxe-mode
FLAVOR=$1
PACKAGE=haxe-mode
if [ ${FLAVOR} = emacs22 -o ${FLAVOR} = emacs23 -o ${FLAVOR} = emacs-snapshot ]; then
    echo remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}
    rm -rf /usr/share/${FLAVOR}/site-lisp/${PACKAGE}
fi
exit 0
