.TH HAXEDOC 1 "Nov 6, 2006" ""
.SH NAME
haxedoc \- Haxe Documentation Generator
.SH SYNOPSIS
\fBhaxedoc\fR [xmlfiles...] [\fB-f \fIfilter\fR]
.SH DESCRIPTION
.PP
haxedoc is a command-line tool to produce documentation from haXe programs.
.SH AUTHOR
haXe is written by Nicolas Cannasse for Motion-Twin.
.SH SEE ALSO
.BR "haxe" (1),
.SH WEB
.IR "http://haxe.org" .
